name: flutter_to_do_list
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1
  msh_checkbox: ^2.0.1 
  uuid: ^4.4.0
  cupertino_icons: ^1.0.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/list_icon.PNG"

flutter:
  uses-material-design: true

  assets:
    - images/
